<a  data-options="plain:true,iconCls:'icon-group'" class="easyui-linkbutton" href="/mySafeArea/Jsps/population.jsp?target=0" style="background:<%if(target==0){%>#ffe48d<%}else{ %>white<%} %>" >人口管理</a>

<a  data-options="plain:true,iconCls:'icon-group'" class="easyui-linkbutton" href="/mySafeArea/Jsps/populationSummary.jsp?target=6" style="background:<%if(target==6){%>#ffe48d<%}else{ %>white<%} %>" >人口统计信息</a>

<a  data-options="plain:true,iconCls:'icon-house'" class="easyui-linkbutton" href="/mySafeArea/Jsps/house.jsp?target=1" style="background:<%if(target==1){%>#ffe48d<%}else{ %>white<%} %>" >房屋管理</a>

<a  data-options="plain:true,iconCls:'icon-house'" class="easyui-linkbutton" href="/mySafeArea/Jsps/houseSummary.jsp?target=7" style="background:<%if(target==7){%>#ffe48d<%}else{ %>white<%} %>" >房屋统计信息</a>

<a  data-options="plain:true,iconCls:'icon-car'" class="easyui-linkbutton" href="/mySafeArea/Jsps/car.jsp?target=2" style="background:<%if(target==2){%>#ffe48d<%}else{ %>white<%} %>"  >车辆管理</a>

<a  data-options="plain:true,iconCls:'icon-car'" class="easyui-linkbutton" href="/mySafeArea/Jsps/carSummary.jsp?target=8" style="background:<%if(target==8){%>#ffe48d<%}else{ %>white<%} %>"  >车辆统计信息</a>

<a data-options="plain:true,iconCls:'icon-shop'" class="easyui-linkbutton" href="/mySafeArea/Jsps/shop.jsp?target=3" style="background:<%if(target==3){%>#ffe48d<%}else{ %>white<%} %>" >商铺管理</a>

<a data-options="plain:true,iconCls:'icon-shop'" class="easyui-linkbutton" href="/mySafeArea/Jsps/shopSummary.jsp?target=9" style="background:<%if(target==9){%>#ffe48d<%}else{ %>white<%} %>" >商铺统计信息</a>

<a data-options="plain:true,iconCls:'icon-new'" class="easyui-linkbutton" href="/mySafeArea/Jsps/news.jsp?target=4" style="background:<%if(target==4){%>#ffe48d<%}else{ %>white<%} %>" >新闻管理</a>


<a data-options="plain:true,iconCls:'icon-notice'" class="easyui-linkbutton" href="/mySafeArea/Jsps/notices.jsp?target=5" style="background:<%if(target==5){%>#ffe48d<%}else{ %>white<%} %>" >公告管理</a>

