<a  data-options="plain:true,iconCls:'icon-notice'" class="easyui-linkbutton" href="/mySafeArea/Jsps/population.jsp?target=0" style="background:<%if(target==0){%>#ffe48d<%}else{ %>white<%} %>" >人员管理</a>

<a  data-options="plain:true,iconCls:'icon-company'" class="easyui-linkbutton" href="/mySafeArea/Jsps/house.jsp?target=1" style="background:<%if(target==1){%>#ffe48d<%}else{ %>white<%} %>" >房屋管理</a>

<a  data-options="plain:true,iconCls:'icon-workshop'" class="easyui-linkbutton" href="/mySafeArea/Jsps/car.jsp?target=2" style="background:<%if(target==2){%>#ffe48d<%}else{ %>white<%} %>"  >车辆管理</a>

<a data-options="plain:true,iconCls:'icon-department'" class="easyui-linkbutton" href="/mySafeArea/Jsps/shop.jsp?target=3" style="background:<%if(target==3){%>#ffe48d<%}else{ %>white<%} %>" >商铺管理</a>

<a data-options="plain:true,iconCls:'icon-group'" class="easyui-linkbutton" href="/mySafeArea/Jsps/news.jsp?target=4" style="background:<%if(target==4){%>#ffe48d<%}else{ %>white<%} %>" >新闻管理</a>


<a data-options="plain:true,iconCls:'icon-group'" class="easyui-linkbutton" href="/mySafeArea/Jsps/notices.jsp?target=5" style="background:<%if(target==5){%>#ffe48d<%}else{ %>white<%} %>" >公告管理</a>

