
<h4>查找商铺</h4>
<p>选择检索的条件，使用下拉框选择。在输入框中输入条件，可多条件 单击<a class="easyui-linkbutton" data-options="iconCls:'icon-ok'">增加条件</a>按钮 然后点击<a class="easyui-linkbutton" data-options="iconCls:'icon-search'">查找</a></p>
<p>当需要重新检索时，可以单击<a class="easyui-linkbutton" >重置查询</a>按钮, 查询条件会重置，再重新输入条件，去查询</p>
<h4>导入</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-import'">导入</a>选择要导入的excel文件单击<a class="easyui-linkbutton" data-options="iconCls:'icon-import'">导入数据</a>就可以将数据导入到系统中</p>
<h4>导出</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-xls'">导出</a>会将所有的查询到的信息导出到excel文档中</p>
